### ISSUE TITLE
micro-front-mono 빌드시 질의입니다.

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#5]
1. mc_common 스키마의 데이터 구조 (및 데이터) SQL 파일이 있는지요?

1.1 레디스 데이터 구조를 따로 설정하지 않아도 되는지요?

2. development, production 모드 변경을 yml 상에서 할 수 있는지요?

2-1. 아래의 레디스 설정 정보가 디폴트로 없는 것 같습니다. application.yml 파일에 넣으면 될까요?
```
spring:
  cache:
    type: jcache
  redis:
    host: #REDIS_ADDRESS
    port: 6379
    password: 
```

**3번 질문은 해결되었습니다. 감사합니다. src/java/ 폴더 아래에 각종 yml 파일이 들어 있는 것을 확인하였습니다.**
3. mvn install 시에 아래와 같은 redisson-dev.yml 파일이 읽기 전용입니다. 원격 레디스 저장소로 사용하면 될까요?
```
singleServerConfig:
  password: "{패스워드}"
  address: "redis://{레디스원격주소}"
```
